import type { GameState } from '../types/game'

const PTS_COLOR: Record<number, string> = {
  5: '#e03030',
  4: '#f07d20',
  3: '#f5c842',
  0: '#6a8aaa',
}

function ptsColor(pts: number): string {
  return PTS_COLOR[pts] ?? '#6a8aaa'
}

export function exportScoreboard(gameState: GameState): void {
  const sorted = [...gameState.teams].sort((a, b) => b.score - a.score)
  const history = [...gameState.history].reverse()

  const ROW_H = 36
  const HEADER_H = 60
  const SECTION_GAP = 20
  const FOOTER_H = 30
  const W = 560
  const PADDING = 24

  const standingsH = sorted.length * ROW_H + 28
  const histH = history.length > 0 ? history.length * ROW_H + 28 : 0
  const totalH = HEADER_H + standingsH + (history.length > 0 ? SECTION_GAP + histH : 0) + SECTION_GAP + FOOTER_H + PADDING * 2

  const svg = `
<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${totalH}" font-family="monospace">
  <rect width="${W}" height="${totalH}" fill="#07111c"/>

  <!-- Title -->
  <text x="${W / 2}" y="38" text-anchor="middle" fill="#00d4ff" font-size="22" font-weight="bold" letter-spacing="4">WAVELENGTH</text>
  <text x="${W / 2}" y="56" text-anchor="middle" fill="#6a8aaa" font-size="11" letter-spacing="2">SCOREBOARD · Round ${gameState.roundNumber}</text>

  <!-- Standings header -->
  <text x="${PADDING}" y="${HEADER_H + 18}" fill="#6a8aaa" font-size="10" letter-spacing="2" font-weight="bold">STANDINGS</text>
  ${sorted.map((team, rank) => {
    const y = HEADER_H + 28 + rank * ROW_H
    const bg = rank === 0 ? 'rgba(0,212,255,0.08)' : 'rgba(255,255,255,0.03)'
    return `
  <rect x="${PADDING}" y="${y}" width="${W - PADDING * 2}" height="${ROW_H - 4}" rx="6" fill="${bg}"/>
  <text x="${PADDING + 10}" y="${y + 22}" fill="#6a8aaa" font-size="12">#${rank + 1}</text>
  <text x="${PADDING + 38}" y="${y + 22}" fill="#e8edf2" font-size="14" font-weight="bold">${esc(team.name)}</text>
  <text x="${PADDING + 38}" y="${y + 32}" fill="#6a8aaa" font-size="10">${esc(team.members[0])} &amp; ${esc(team.members[1])}</text>
  <text x="${W - PADDING - 10}" y="${y + 24}" text-anchor="end" fill="#00d4ff" font-size="18" font-weight="bold">${team.score}</text>`
  }).join('')}

  ${history.length > 0 ? `
  <!-- History header -->
  <text x="${PADDING}" y="${HEADER_H + standingsH + SECTION_GAP + 18}" fill="#6a8aaa" font-size="10" letter-spacing="2" font-weight="bold">ROUND HISTORY</text>
  ${history.map((r, i) => {
    const y = HEADER_H + standingsH + SECTION_GAP + 28 + i * ROW_H
    return `
  <rect x="${PADDING}" y="${y}" width="${W - PADDING * 2}" height="${ROW_H - 4}" rx="6" fill="rgba(255,255,255,0.02)"/>
  <text x="${PADDING + 8}" y="${y + 20}" fill="#6a8aaa" font-size="10" font-weight="bold">R${r.roundNumber}</text>
  <text x="${PADDING + 36}" y="${y + 20}" fill="#e8edf2" font-size="12" font-weight="bold">${esc(r.teamName)}</text>
  <text x="${PADDING + 36}" y="${y + 32}" fill="#6a8aaa" font-size="10">${esc(r.clueGiver)} → ${esc(r.guesser)}${r.clue ? `  "${esc(r.clue)}"` : ''}</text>
  <text x="${W - PADDING - 8}" y="${y + 22}" text-anchor="end" fill="${ptsColor(r.points)}" font-size="13" font-weight="bold">${r.points}pts</text>`
  }).join('')}` : ''}

  <!-- Footer -->
  <text x="${W / 2}" y="${totalH - 10}" text-anchor="middle" fill="#1e3552" font-size="10">Generated by GameTool</text>
</svg>`.trim()

  const blob = new Blob([svg], { type: 'image/svg+xml' })
  const url = URL.createObjectURL(blob)

  // Convert SVG → Canvas → PNG via Image
  const img = new Image()
  img.onload = () => {
    const canvas = document.createElement('canvas')
    canvas.width = W * 2
    canvas.height = totalH * 2
    const ctx = canvas.getContext('2d')!
    ctx.scale(2, 2)
    ctx.drawImage(img, 0, 0)
    URL.revokeObjectURL(url)
    canvas.toBlob(pngBlob => {
      if (!pngBlob) return
      const a = document.createElement('a')
      a.href = URL.createObjectURL(pngBlob)
      a.download = `wavelength-scoreboard-r${gameState.roundNumber}.png`
      a.click()
      setTimeout(() => URL.revokeObjectURL(a.href), 10000)
    }, 'image/png')
  }
  img.src = url
}

function esc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}
